/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    AffixTools: typeof import('./../components/AffixTools.vue')['default']
    Author: typeof import('./../components/Sidebar/Author.vue')['default']
    Catelog: typeof import('./../components/Catelog.vue')['default']
    Comment: typeof import('./../components/comment/index.vue')['default']
    DayNightTog: typeof import('./../components/DayNightTog.vue')['default']
    DayNightToggle: typeof import('./../components/DayNightToggle.vue')['default']
    Echarts: typeof import('./../components/Echarts.vue')['default']
    EmailDialog: typeof import('./../components/dialog/EmailDialog.vue')['default']
    Emoji: typeof import('./../components/Emoji.vue')['default']
    LoadViewer: typeof import('./../components/LoadViewer.vue')['default']
    LoginDialog: typeof import('./../components/dialog/LoginDialog.vue')['default']
    MyImage: typeof import('./../components/MyImage.vue')['default']
    NaiveProvider: typeof import('./../components/NaiveProvider.vue')['default']
    NAvatar: typeof import('naive-ui')['NAvatar']
    NButton: typeof import('naive-ui')['NButton']
    NConfigProvider: typeof import('naive-ui')['NConfigProvider']
    NDialogProvider: typeof import('naive-ui')['NDialogProvider']
    NDrawer: typeof import('naive-ui')['NDrawer']
    NDrawerContent: typeof import('naive-ui')['NDrawerContent']
    NEllipsis: typeof import('naive-ui')['NEllipsis']
    NForm: typeof import('naive-ui')['NForm']
    NFormItem: typeof import('naive-ui')['NFormItem']
    NGradientText: typeof import('naive-ui')['NGradientText']
    NImage: typeof import('naive-ui')['NImage']
    NInput: typeof import('naive-ui')['NInput']
    NInputGroup: typeof import('naive-ui')['NInputGroup']
    NMessageProvider: typeof import('naive-ui')['NMessageProvider']
    NModal: typeof import('naive-ui')['NModal']
    NNotificationProvider: typeof import('naive-ui')['NNotificationProvider']
    Notice: typeof import('./../components/Sidebar/Notice.vue')['default']
    NPagination: typeof import('naive-ui')['NPagination']
    NPopover: typeof import('naive-ui')['NPopover']
    NSkeleton: typeof import('naive-ui')['NSkeleton']
    NSpace: typeof import('naive-ui')['NSpace']
    Pagination: typeof import('./../components/Pagination.vue')['default']
    Paging: typeof import('./../components/Paging.vue')['default']
    Password: typeof import('./../components/dialog/Password.vue')['default']
    PasswordDialog: typeof import('./../components/dialog/PasswordDialog.vue')['default']
    RecentComment: typeof import('./../components/Sidebar/RecentComment.vue')['default']
    RegisterDialog: typeof import('./../components/dialog/RegisterDialog.vue')['default']
    ReplyBox: typeof import('./../components/comment/ReplyBox.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Sidebar: typeof import('./../components/Sidebar/index.vue')['default']
    SvgIcon: typeof import('./../components/SvgIcon.vue')['default']
    Waves: typeof import('./../components/Waves.vue')['default']
    WebInfo: typeof import('./../components/Sidebar/WebInfo.vue')['default']
  }
}
